### PR TITLE
fixes `eventToHotkeyString` returns doubled "modifier" when "key" is a modifier

### LINKED ISSUE #60: `eventToHotkeyString ` returns doubled "modifier" when "key" is a modifier
Because of the way `eventToHotkeyString` works, it will return a "double modifier" for a key-combination where a modifier key (`Control`, `Alt`, `Meta`, or `Shift`) is also the `event.key`.

This is visible by looking at the hotkey mapper tool:

Screen Shot 2021-12-15 at 9 50 36 AM

## To Reproduce:

1. Visit https://github.github.io/hotkey/examples/hotkey_mapper.html
2. Input a `ctrl`.
3. Observe the hotkey string is `Control+Control`.
4. Without lifting your finger from the `crtl` key, input a `shift` key.
5. Observe the hotkey string is `Control+Shift+Shift`.
6. Lift your fingers.
7. Input a `shift`.
8. Observe the hotkey string is `Shift+Shift`.
9. Input a `ctrl`.
10. Observe the hotkey string is `Control+Shift+Control`.
11. Note that the hotkey string in 10 is different than the hotkey string in 5: this is due to the order that these keys were pressed.

https://user-images.githubusercontent.com/2694/146212176-820f16cb-91c2-4a3c-99e3-8b9d7824092c.mov

## Expected

When the `event.key` is a modifier, it should only appear once in the hotkey string. The order that modifiers appear in the string should be consistent, regarldless of the order that keys are pressed (see 11 in repro steps above).

There are two possibilities:

1. Filter out the modifier when it is the same as the `event.key`
    2. `ctrl` then `shift` would now be: `[Control+]Shift+Control`: `Shift+Control`
    3. `shift` then `ctrl` would be `Control+[Shift+]Shift`: `Control+Shift`
2. When the `vent.key` is a modifier, don't map it to the stirng
    2. `ctrl` then `shift` would now be: `Control+Shift+[Control]`: `Control+Shift+`
    3. `shift` then `ctrl` would be `Control+Shift+[Shift]`: `Control+Shift+`

So the solution is to do 2. But we'll have to avoid the trailing `+`

### PR DESCRIPTION
**Pull request by theinterned**
resolves #60 

This PR fixes a bug where `eventToHotkeyString` was returning a "double modifier" for a key-combination where a modifier key (`Control`, `Alt`, `Meta`, or `Shift`) is also the `event.key`.

This PR updates `eventToHotkeyString` so that the resulting string still presents modifiers in a consistent order. 

For more details see #60 

| Before | After |
| ---| --- |
| Screen Shot 2021-12-15 at 9 50 36 AM | Screen Shot 2021-12-16 at 5 58 21 PM |

## Screencast of the after

https://user-images.githubusercontent.com/2694/146461487-c3832946-788c-47be-a3f3-eadfe712a5e7.mov

## Breaking change

Although the previous behaviour was likely a bug, this is a breaking change in that it changes the "hotkey string" format when a modifier key is used as the `hotkey` (the final element in a hotkey string sequence) for example `Meta+Shift+Shift` becomes `Meta+Shift` after this change.

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -218,7 +218,9 @@ describe('hotkey', function () {
       ['Control+Shift+`', {ctrlKey: true, shiftKey: true, key: '`'}],
       ['c', {key: 'c', code: 'KeyC'}],
       ['S', {key: 'S', shiftKey: true, code: 'KeyS'}],
-      ['!', {key: '!', shiftKey: true, code: 'KeyS'}]
+      ['!', {key: '!', shiftKey: true, code: 'KeyS'}],
+      ['Control+Shift', {ctrlKey: true, shiftKey: true, key: 'Shift'}],
+      ['Control+Shift', {ctrlKey: true, shiftKey: true, key: 'Control'}]
```
Comment (theinterned) [inline test/test.js:223]: These were initially failing with:

```sh
FAILED TESTS:
  hotkey
    eventToHotkeyString
      ✖ {"ctrlKey":true,"shiftKey":true,"key":"Shift"} => Control+Shift
        Chrome Headless 96.0.4664.110 (Mac OS 10.15.7)
      Error: Uncaught AssertionError: expected 'Control+Shift+Shift' to equal 'Control+Shift' (node_modules/chai/chai.js:250)
          at Context.<anonymous> (test/test.js:232:23)

      ✖ {"ctrlKey":true,"shiftKey":true,"key":"Control"} => Control+Shift
        Chrome Headless 96.0.4664.110 (Mac OS 10.15.7)
      Error: Uncaught AssertionError: expected 'Control+Shift+Control' to equal 'Control+Shift' (node_modules/chai/chai.js:250)
          at Context.<anonymous> (test/test.js:232:23)
```

**Comment by theinterned** [comment]
I wonder if you reviewers would consider this a breaking change? It is arguably as the format of the string does change.

**Review by keithamus — APPROVED** [review]
This looks good :+1: 

I do think it's a breaking change. Maybe we should rip the band-aid off with a breaking change that reworks the format?
